import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-calibri antialiased w-full flex justify-center`}
      >
        <div className="mx-auto w-full max-w-[1440px] relative">{children}</div>
      </body>
    </html>
  );
}
